### ISSUE TITLE
QtQuick setup problems

### ISSUE THREAD

**Issue by antoinechauvn** [Prx001/Python-Qt-examples#1]
Hi, I recently had a problem with QtQuick setup for python (using QtCreator).

Could you help me ? 

my discord: Armanta#6184

**Comment by Prx001** [comment]
Hi Antoine,
I haven't worked much with QtQuick as you can see in the repo (just a hello world app there),
But I may be able to help you through your problem if you describe it well.

**Comment by antoinechauvn** [comment]
I think i'll need to stream you the problem :/

If you can add me
